### PR TITLE
Fix breakpoint setting with custom sourceDirs

### LINKED ISSUE #9: Source dirs priority issue when setting breakpoints
Our project is organised (for some reason):
```
project/src/components/...
project/src/source/main.brs
```
So `bsconfig.json` has: `rootDir: "."` and `sourceRoot: "src/"` 

And VSCode `launch.json` for debugging has: `"sourceDirs": [ "${workspaceFolder}/src" ]`

Now the problem is that `BreakpointManager` calls `LocationManager.getStagingLocations` with source roots in this order:
- `project/`
- `project/src/`

which **crashes** during breakpoint insertion because it tries to create a breakpoint in `project/out/.staging/src/source/main.brs`

### PR DESCRIPTION
**Pull request by elsassph**
Fixes #9 

- Prevent crash if target breakpoint file doesn't exist
- change sourceDirs order to priorities sourceDirs over rootDir

I know it would be worth adding new tests but that's a lot to figure here.

### CODE REVIEW

File: src/managers/BreakpointManager.ts [hunk 1]
```diff
@@ -234,13 +236,21 @@ export class BreakpointManager {
...
         await Promise.all(promises);
     }
 
     /**
      * Write breakpoints to the specified file, and update the sourcemaps to match
      */
     private async writeBreakpointsToFile(stagingFilePath: string, breakpoints: BreakpointWorkItem[]) {
+
+        //do not crash if the file doesn't exist
+        if (!fsExtra.existsSync(stagingFilePath)) {
```
Comment (TwitchBronBron) [inline src/managers/BreakpointManager.ts:249]: Can you change this to async `if (!await fsExtra.exists(stagingFilePath)`?Look above around line 237, we call this method for each file all at the same time, so running a synchronous file operation will block other operations from working during that time.

File: src/managers/BreakpointManager.ts [hunk 2]
```diff
@@ -166,8 +168,8 @@ export class BreakpointManager {
                     breakpoint.line,
                     breakpoint.column,
                     [
-                        project.rootDir,
-                        ...project.sourceDirs
+                        ...project.sourceDirs,
+                        project.rootDir
```
Comment (TwitchBronBron) [inline src/managers/BreakpointManager.ts:172]: Interesting. I didn't think this was right at first, but now that I think about it more, I'm starting to see the issue. 

In situations when we are using sourceDirs, the `rootDir` becomes kind of a "staging folder" itself. In that situation, we actually want to walk backwards through the sourceDirs first. Otherwise, we are most likely going to find the file in `rootDir` every time. So by moving it to the end, that solve the issue. Nice catch.

**Comment by TwitchBronBron** [comment]
@elsassph I'm ok with this PR. However, before I merge it, I would like to resolve our conversation in #9 first to make sure this solves your issue when using the correct launch/bsconfig settings.

File: src/managers/BreakpointManager.ts (hunk 1 above)
Comment (elsassph) [reply src/managers/BreakpointManager.ts:249]: I was looking to do that but this method isn't `await` friendly: it still requires a callback.

File: src/managers/BreakpointManager.ts (hunk 2 above)
Comment (elsassph) [reply src/managers/BreakpointManager.ts:172]: Exactly.

File: src/managers/BreakpointManager.ts (hunk 1 above)
Comment (TwitchBronBron) [reply src/managers/BreakpointManager.ts:249]: `fsExtra` wraps a bunch of the `fs` methods and makes them promise-ready. Apparently it doesn't do that for `exists`. So check out [fsExtra.pathExists](https://github.com/jprichardson/node-fs-extra/blob/HEAD/docs/pathExists.md) instead. That one has support for promises and does the same thing.

Comment (elsassph) [reply src/managers/BreakpointManager.ts]: Gotcha - fixed.
